name: 'modify-tabs'
description: '修改 tab'
inputs:
  url:
    description: '图片的 URL'
    required: true
  op_type:
    description: '操作类型'
    required: true
  src:
    description: '项目 src'
    default: './src'
  dist:
    description: '图标文件名称'
    default: './src/static/tab/cts_tab.png'
  page_path:
    description: 'tab path'
    default: 'pages/cts/index'
  tab_name:
    description: 'tab name'
    required: true
  app_name:
    description: 'app name'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
